"""Integration routes for external service OAuth flows."""

from __future__ import annotations

import pathlib
import sys

if __package__ in (None, ""):
    # Allow running this file directly for local debugging.
    project_root = pathlib.Path(__file__).resolve().parents[3]
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))

import os
from typing import Any, Dict
import json

import httpx
from fastapi import APIRouter, Depends, HTTPException, Query
import structlog
from sqlalchemy.ext.asyncio import AsyncSession

from app.config.settings import settings
from app.database.session import get_db

router = APIRouter()
log = structlog.get_logger()


def _load_cached_pkce_data() -> Dict[str, Any]:
    """Load the most recent PKCE values written by the dev launcher."""
    cache_file = settings.SALESFORCE_PKCE_CACHE_FILE
    if not os.path.exists(cache_file):
        return {}

    try:
        with open(cache_file, "r", encoding="utf-8") as f:
            data = json.load(f)
            if isinstance(data, dict):
                return data
    except (IOError, json.JSONDecodeError) as exc:
        log.warning("Failed to load PKCE cache.", error=str(exc), cache_file=cache_file)

    return {}


@router.get("/salesforce/oauth/callback")
@router.get("/salesforce/callback")
async def salesforce_oauth_callback(
    code: str = Query(..., description="Authorization code from Salesforce"),
    state: str | None = Query(None, description="OAuth state returned by Salesforce"),
) -> Dict[str, Any]:
    """
    Handles the OAuth2 callback from Salesforce and exchanges the authorization
    code for an access token using the PKCE flow.
    """
    log.info("Salesforce OAuth callback route accessed.")

    normalized_code = code.strip()
    if normalized_code.lower() in {"test", "dummy", "example"}:
        raise HTTPException(
            status_code=400,
            detail={
                "error": "invalid_authorization_code",
                "message": (
                    "The callback must receive a real Salesforce authorization code from the browser "
                    "redirect. Do not call this endpoint manually with code=test."
                ),
            },
        )

    cached_pkce = _load_cached_pkce_data()
    cached_state = cached_pkce.get("state")

    if state and cached_state and state != cached_state:
        raise HTTPException(status_code=400, detail="OAuth state mismatch.")

    # Prefer file-backed cache; fallback to env var for legacy/dev compatibility.
    code_verifier = cached_pkce.get("code_verifier") or os.getenv("DEV_PKCE_CODE_VERIFIER")
    if not code_verifier:
        raise HTTPException(
            status_code=500,
            detail="PKCE code_verifier not found. Start auth flow from run_dev.py before callback.",
        )

    token_url = f"{settings.SALESFORCE_LOGIN_URL.rstrip('/')}/services/oauth2/token"
    payload = {
        "grant_type": "authorization_code",
        "client_id": settings.SALESFORCE_CLIENT_ID,
        "client_secret": settings.SALESFORCE_CLIENT_SECRET,
        "redirect_uri": cached_pkce.get("redirect_uri") or str(settings.SALESFORCE_REDIRECT_URI),
        "code": code,
        "code_verifier": code_verifier,
    }

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(token_url, data=payload)

    if response.status_code >= 400:
        try:
            error_payload = response.json()
        except ValueError:
            error_payload = {"error": "token_exchange_failed", "error_description": response.text}

        detail = {
            "salesforce_error": error_payload,
            "hint": (
                "Use the exact callback URL generated by run_dev.py and complete OAuth from the authorize URL. "
                "Token exchange can fail if the code is expired/reused, the redirect URI mismatches, "
                "or the wrong Salesforce login domain is used (login vs test)."
            ),
        }

        log.error(
            "Salesforce token exchange failed",
            status_code=response.status_code,
            response_body=response.text,
            hint=detail["hint"],
        )
        raise HTTPException(status_code=response.status_code, detail=detail)

    token_data = response.json()

    # For development, cache the token locally to avoid re-authenticating.
    try:
        with open(settings.SALESFORCE_TOKEN_FILE, "w") as f:
            json.dump(token_data, f)
        log.info("Salesforce token cached locally.", file=settings.SALESFORCE_TOKEN_FILE)
    except IOError as e:
        log.error("Failed to cache Salesforce token.", error=str(e))

    log.info("Successfully exchanged code for Salesforce access token.")
    return token_data


if __name__ == "__main__":
    print(
        "Run this route through the API server instead of executing it directly:\n"
        "  c:/Users/angel/Desktop/insightforge/.venv/Scripts/python.exe -m uvicorn app.main:app --host 127.0.0.1 --port 8000"
    )
