"""Defines the shared data context for agent communication."""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

from app.models.ticket import TicketStatus, TicketPriority


class CustomerContext(BaseModel):
    """Represents customer information in the shared context."""
    id: int
    name: str
    email: str
    country: Optional[str] = None
    previous_ticket_count: int = 0


class TicketContext(BaseModel):
    """Represents the current ticket's information."""
    id: int
    subject: str
    description: str
    status: TicketStatus
    priority: TicketPriority


class SharedContext(BaseModel):
    """
    A structured data object passed between agents.

    Agents read from and write to this context, but never call each other.
    The Supervisor agent is responsible for routing the context to the appropriate agent.
    """
    ticket: TicketContext
    customer: CustomerContext
    history: List[Dict[str, Any]] = Field(default_factory=list, description="History of changes and comments on the ticket.")

    # Fields populated by agents
    language: Optional[str] = Field(None, description="Detected language of the ticket (e.g., 'en', 'es').")
    classification: Optional[Dict[str, Any]] = Field(None, description="Ticket classification results (category, sentiment).")
    knowledge_snippets: List[Dict[str, Any]] = Field(default_factory=list, description="Relevant snippets from the knowledge base.")
    generated_sql_query: Optional[str] = Field(None, description="SQL query generated by the SQL Agent.")
    sql_query_results: Optional[List[Dict[str, Any]]] = Field(None, description="Results from executing the generated SQL.")
    suggested_response: Optional[str] = Field(None, description="The draft response for the customer.")
    escalation_required: bool = Field(False, description="Flag indicating if human review is needed.")
    escalation_reason: Optional[str] = Field(None, description="Justification for the escalation decision.")